### ISSUE TITLE
[v3][Android/iOS] Unable to resolve module ./TouchableItem

### ISSUE THREAD

**Issue by rapomon** [satya164/react-native-tab-view#1150]
I'm using the following package versions:

- `react-native 0.64.0`
- `react-native-tab-view 3.0.0`
- `react-native-pager-view 5.1.2`

```
Error: Unable to resolve module ./TouchableItem from C:\nodejs\mahle-one-app\node_modules\react-native-tab-view\lib\module\index.js:

None of these files exist:
  * node_modules\react-native-tab-view\lib\module\TouchableItem(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * node_modules\react-native-tab-view\lib\module\TouchableItem\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
> 1 | export { default as TabBar } from './TabBar';
  2 | export { default as TabView } from './TabView';
  3 | export { default as TabBarIndicator } from './TabBarIndicator';
  4 | export { default as TabBarItem } from './TabBarItem';
    at ModuleResolver.resolveDependency (C:\nodejs\mahle-one-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (C:\nodejs\mahle-one-app\node_modules\metro\src\node-haste\DependencyGraph.js:413:43)
    at Object.resolve (C:\nodejs\mahle-one-app\node_modules\metro\src\lib\transformHelpers.js:317:42)
    at resolve (C:\nodejs\mahle-one-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:629:33)
    at C:\nodejs\mahle-one-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\nodejs\mahle-one-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:644:33)
    at C:\nodejs\mahle-one-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\nodejs\mahle-one-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:24)

```

**Comment by TheWirv** [comment]
`TouchableItem` has been replaced with `PlatformPressable`, as far as I see it.

**Comment by rapomon** [comment]
Thank you, after re-install the module it works fine.

**Comment by karo-dc** [comment]
@rapomon I have the same issue and can not fix it. How you have fixed?

**Comment by rapomon** [comment]
Uninstall the module, and install again, this should work.

**Comment by karo-dc** [comment]
I have tried, but again the same, ok, thank  :(

**Comment by rapomon** [comment]
Maybe you can try to remove node_modules and do a clean install.
Also you can do this from the root project folder:
`cd android && gradlew clean`

**Comment by karo-dc** [comment]
android worked well, the problem in iosm I have removed all then install again, same.

**Comment by rapomon** [comment]
Ok, sorry but I only use Android for my app.

**Comment by karo-dc** [comment]
ok, thanks.

**Comment by karo-dc** [comment]
thanks for renaiming

**Comment by rapomon** [comment]
Openning again the issue so in iOS currently there is not a solution.

**Comment by satya164** [comment]
There's no file in the library which imports `TouchableItem`. If you have issues, it's due to cache. So you need to clear your cache if you have the issue: https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version
