### ISSUE TITLE
[v3][Android] Native crash - Unable to find JSIModule for class UIManager

### ISSUE THREAD

**Issue by DanielMarkiel** [satya164/react-native-tab-view#1157]
### Current behaviour

If both `react-native-tab-view` and `@react-native-picker/picker` are rendered on the same screen, the app crashes on picker press.

### Expected behaviour

Application shouldn't crash.

### Code sample

https://github.com/DanielMarkiel/reprex-rn-jsi-module-error

### Logcat

```
  --------- beginning of crash
2021-03-26 12:46:32.828 14238-14238/com.reprexrnjsimoduleerror E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.reprexrnjsimoduleerror, PID: 14238
    java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
        at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
        at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
        at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2664)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
2021-03-26 12:46:32.828 14238-14238/com.reprexrnjsimoduleerror E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### What have you tried

I was able to fix the issue by downgrading `react-native-tab-view` to v2.16.0.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| expo                         | -
| react-native                 | 0.64.0
| react-native-tab-view        | 3.0.0
| react-native-pager-view      | 5.1.2
| node                         | 14.16.0
| npm or yarn                  | yarn

**Comment by HimiGame** [comment]
downgraded react-native-tab-view 3.0.0 to v2.16.0  
can  solve

**Comment by jafar-jabr** [comment]
+1

**Comment by mikehardy** [comment]
@jafar-jabr 

1. +1 comments are comment spam for everyone. Don't do it - use reactions on the issues instead
2. this is resolved by https://github.com/facebook/react-native/commit/b0e8c1eac0a9edda12ecfa264209a8b3222afe27 - which is on master in main repo and has been picked to release-0.65 and requested for any future 0.64.x release (though I'm not aware of one being planned)

@satya164 this should be resolved via reference to upstream issue https://github.com/facebook/react-native/issues/31245 which should itself be closed via commit I referenced

Cheers!

**Comment by satya164** [comment]
@mikehardy thank you. closing the issue then

**Comment by jafar-jabr** [comment]
@mikehardy understood, thought that if the issue has more participants it will track the attention :))
