### ISSUE TITLE
Adding and using '@react-navigation/material-top-tabs' in Expo Tabbed (typescript) returns error with this library

### ISSUE THREAD

**Issue by fuzkabir** [satya164/react-native-tab-view#1183]
### Current behaviour

it runs perfectly with web
but android emulator( android studio) returns error

expo metro bundler shows error message
### Expected behaviour

I installed latest Expo project. Initialized a tabbed (type script) managed project. 
it ran perfectly with emulator.
I wanted to show my bottom tabs on top. so, I added these libraries :

+ react-native-reanimated@2.1.0
+ react-native-tab-view@3.0.1
+ @react-navigation/material-top-tabs@5.3.15

in navigation/BottomTabNavigator.tsx
I added this line :
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';

and alter this line 
const BottomTab = createBottomTabNavigator<BottomTabParamList>();
to:
const BottomTab = createMaterialTopTabNavigator<BottomTabParamList>();

then it shows error:
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  3 | import ViewPager, {
  4 |   PageScrollStateChangedNativeEvent,
> 5 | } from 'react-native-pager-view';
    |         ^
  6 | import useAnimatedValue from './useAnimatedValue';
  7 | import {
  8 |   NavigationState,
at node_modules\metro\src\lib\bundle-modules\HMRClient.js:261:21 in deletedIDs.forEach$argument_0
at node_modules\metro\src\lib\bundle-modules\HMRClient.js:189:2 in _flushQueue
at http://192.168.0.101:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:35642:34 in emit
at http://192.168.0.101:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:35395:22 in onmessage
at node_modules\react-native\Libraries\EventEmitter\NativeEventEmitter.js:49:5 in addListener
at http://192.168.0.101:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:33675:30 in <unknown>
at http://192.168.0.101:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3967:41 in emit
at node_modules\react-native\Libraries\Utilities\stringifySafe.js:89:7 in stringifySafe
at node_modules\react-native\Libraries\Performance\Systrace.js:29:11 in mark
at http://192.168.0.101:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3107:14 in __guard
at node_modules\react-native\Libraries\Performance\Systrace.js:27:6 in <global>
at [native code]:null in callFunctionReturnFlushedQueue

I did the steps

then it shows
Failed building JavaScript bundle.
Unable to resolve module react-native-pager-view from C:\reactnative\tabbed\node_modules\react-native-tab-view\src\Pager.native.tsx: react-native-pager-view could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  3 | import ViewPager, {
  4 |   PageScrollStateChangedNativeEvent,
> 5 | } from 'react-native-pager-view';
    |         ^
  6 | import useAnimatedValue from './useAnimatedValue';
  7 | import {
  8 |   NavigationState,
 
but there's the index.ts file. but it has no main   
### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

the BottomTabNavigator.tsx,  i don't know or have time to run it in snack.expo.io

/**
 * Learn more about createBottomTabNavigator:
 * https://reactnavigation.org/docs/bottom-tab-navigator
 */

import { Ionicons } from '@expo/vector-icons';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';

import { createStackNavigator } from '@react-navigation/stack';
import * as React from 'react';

import Colors from '../constants/Colors';
import useColorScheme from '../hooks/useColorScheme';
import TabOneScreen from '../screens/TabOneScreen';
import TabTwoScreen from '../screens/TabTwoScreen';
import { BottomTabParamList, TabOneParamList, TabTwoParamList } from '../types';

//const BottomTab = createBottomTabNavigator<BottomTabParamList>();
const BottomTab = createMaterialTopTabNavigator<BottomTabParamList>();

export default function BottomTabNavigator() {
  const colorScheme = useColorScheme();

  return (
    <BottomTab.Navigator
      initialRouteName="TabOne"
      tabBarOptions={{ activeTintColor: Colors[colorScheme].tint }}>
      <BottomTab.Screen
        name="TabOne"
        component={TabOneNavigator}
        options={{
          tabBarIcon: ({ color }) => <TabBarIcon name="ios-code" color={color} />,
        }}
      />
      <BottomTab.Screen
        name="TabTwo"
        component={TabTwoNavigator}
        options={{
          tabBarIcon: ({ color }) => <TabBarIcon name="ios-code" color={color} />,
        }}
      />
    </BottomTab.Navigator>
  );
}

// You can explore the built-in icon families and icons on the web at:
// https://icons.expo.fyi/
function TabBarIcon(props: { name: React.ComponentProps<typeof Ionicons>['name']; color: string }) {
  return <Ionicons size={30} style={{ marginBottom: -3 }} {...props} />;
}

// Each tab has its own navigation stack, you can read more about this pattern here:
// https://reactnavigation.org/docs/tab-based-navigation#a-stack-navigator-for-each-tab
const TabOneStack = createStackNavigator<TabOneParamList>();

function TabOneNavigator() {
  return (
    <TabOneStack.Navigator>
      <TabOneStack.Screen
        name="TabOneScreen"
        component={TabOneScreen}
        options={{ headerTitle: 'Tab One Title' }}
      />
    </TabOneStack.Navigator>
  );
}

const TabTwoStack = createStackNavigator<TabTwoParamList>();

function TabTwoNavigator() {
  return (
    <TabTwoStack.Navigator>
      <TabTwoStack.Screen
        name="TabTwoScreen"
        component={TabTwoScreen}
        options={{ headerTitle: 'Tab Two Title' }}
      />
    </TabTwoStack.Navigator>
  );
}

### What have you tried
tried with new project in expo with just these changes and happened the same. Today I tried with a different PC, it results the same.

 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

no issues found but the same error message
### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |  android 10 (emulator)
| expo                         |  4.4.3
| react-native                 | 0.63.2
| react-native-tab-view        |3.0.1
| react-native-pager-view      | 5.1.9
| node                         | 14.16.1
| npm or yarn                  |6.14.12

**Comment by fuzkabir** [comment]
Yes.
