### ISSUE TITLE
RTL crash on tapping Tab platform:Android

### ISSUE THREAD

**Issue by nagarajbalan** [satya164/react-native-tab-view#1209]
### Current behaviour

Launch the application in RTL(Arabic) language. Tap on the tab or swipe screen is getting crash. Tested in example app as well and app got crashed.

### Expected behaviour

App should not get crash in RTL.

### Versions
"react-native": "0.63.4",
"react-native-tab-view": "^3.0.0",
"react-native-pager-view": "^5.1.2",

### Crash Log
--------- beginning of crash
2021-07-21 15:35:58.139 22673-22673/com.xxx.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx.xxx, PID: 22673
    java.lang.IllegalStateException: **Page can only be offset by a positive amount, not by -372**
        at androidx.viewpager2.widget.ScrollEventAdapter.updateScrollEventValues(ScrollEventAdapter.java:280)
        at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:178)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1040)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Reference: https://github.com/callstack/react-native-pager-view/issues/324**

**Comment by tarouboy** [comment]
Please re-open the issue I am getting the same issue as well.
